USE [ODS_LANDING]
GO

/****** Object:  Table [sn].[LAND_CHANGE_REQUEST]    Script Date: 4/9/2014 7:35:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

PRINT 'Creating table LAND_CHANGE_REQUEST. Started at: ' + CONVERT(VARCHAR(20), GETUTCDATE(), 120)
GO

IF EXISTS(SELECT 1 FROM sys.objects where name = 'LAND_CHANGE_REQUEST') DROP TABLE [sn].[LAND_CHANGE_REQUEST]

CREATE TABLE [sn].[LAND_CHANGE_REQUEST](
	[BACKOUT_PLAN] [varchar](4000) NULL,
	[CAB_DATE] [datetime] NULL,
	[CAB_RECOMMENDATION] [varchar](4000) NULL,
	[CATEGORY] [varchar](40) NULL,
	[CHANGE_PLAN] [varchar](4000) NULL,
	[CONFLICT_STATUS] [varchar](40) NULL,
	[PLANNED_END_DATE] [datetime] NULL,
	[IMPLEMENTATION_PLAN] [varchar](4000) NULL,
	[JUSTIFICATION] [varchar](4000) NULL,
	[OUTSIDE_MAINTENANCE_SCHEDULE] [varchar](5) NULL,
	[PHASE] [varchar](40) NULL,
	[PHASE_STATE] [varchar](40) NULL,
	[PRODUCTION_SYSTEM] [varchar](5) NULL,
	[REASON] [varchar](40) NULL,
	[REQUESTED_BY] [varchar](32) NULL,
	[REQUESTED_BY_DATE] [datetime] NULL,
	[REVIEW_COMMENTS] [varchar](4000) NULL,
	[REVIEW_DATE] [datetime] NULL,
	[REVIEW_STATUS] [int] NULL,
	[RISK] [varchar](50) NULL,
	[SCOPE] [varchar](50) NULL,
	[PLANNED_START_DATE] [datetime] NULL,
	[SYS_ID] [varchar](32) NULL,
	[TEST_PLAN] [varchar](4000) NULL,
	[CHANGE_TYPE] [varchar](40) NULL,
	[ACTUAL_OUTAGE_END_DATE] [datetime] NULL,
	[ACTUAL_OUTAGE_START_DATE] [datetime] NULL,
	[ADVISORY] [varchar](5) NULL,
	[BUILD_TEST_REQUIRED] [varchar](5) NULL,
	[CHANGE_ACCEPTANCE_DATE] [datetime] NULL,
	[CHANGE_BT_APPROVAL_DATE] [datetime] NULL,
	[CHANGE_IMPLEMENTATION_DATE] [datetime] NULL,
	[CHANGE_STATE] [varchar](50) NULL,
	[CLOSURE_STATE] [varchar](40) NULL,
	[CUSTOMER_IMPACTING] [varchar](5) NULL,
	[DATE_OF_FLIGHT] [datetime] NULL,
	[DEVICE_ASSET_NAME] [varchar](40) NULL,
	[FLIGHT_NUMBER] [varchar](40) NULL,
	[IMPLEMENTATION_STATE] [varchar](40) NULL,
	[MAJOR_CHANGE_DATE] [datetime] NULL,
	[NUMBER_OF_TASKS_PAST_DUE] [int] NULL,
	[NUMBER_TYPE_CHANGES] [int] NULL,
	[OUTAGE_ANTICIPATED] [varchar](40) NULL,
	[OUTAGE_INCIDENT] [varchar](32) NULL,
	[PARENT_CHANGE] [varchar](32) NULL,
	[PLANNED_OUTAGE_END_DATE] [datetime] NULL,
	[PLANNED_OUTAGE_START_DATE] [datetime] NULL,
	[RESCHEDULED_CHANGE] [varchar](40) NULL,
	[RESULTING_PROBLEM] [varchar](40) NULL,
	[REVENUE_IMPACTING] [varchar](40) NULL,
	[SEAT_NUMBER] [varchar](40) NULL,
	[SOURCE] [varchar](40) NULL,
	[SOURCE_INCIDENT] [varchar](32) NULL,
	[DRIVING_PROBLEM] [varchar](32) NULL,
	[SPRINT] [varchar](40) NULL,
	[STANDARD_CHANGE] [varchar](5) NULL,
	[SUBMISSION_PRIORITY] [varchar](40) NULL,
	[STANDARD_CHANGE_TEMPLATE] [varchar](32) NULL,
	[ACTIVE] [varchar](5) NULL,
	[ACTIVITY_DUE] [datetime] NULL,
	[APPROVAL_STATE] [varchar](40) NULL,
	[APPROVAL_HISTORY] [varchar](4000) NULL,
	[APPROVAL_SET] [datetime] NULL,
	[ASSIGNED_TO] [varchar](32) NULL,
	[ASSIGNMENT_GROUP] [varchar](32) NULL,
	[BUSINESS_DURATION] [int] NULL,
	[DURATION] [int] NULL,
	[CLOSED] [datetime] NULL,
	[CLOSED_BY] [varchar](32) NULL,
	[RESOLVE_NOTES] [varchar](4000) NULL,
	[CONFIGURATION_ITEM] [varchar](32) NULL,
	[ADDITIONAL_COMMENTS] [varchar](4000) NULL,
	[COMMENTS_AND_WORK_NOTES] [varchar](4000) NULL,
	[COMPANY] [varchar](32) NULL,
	[CONTACT_TYPE] [varchar](40) NULL,
	[CORRELATION_DISPLAY] [varchar](100) NULL,
	[CORRELATION_ID] [varchar](100) NULL,
	[DELIVERY_PLAN] [varchar](32) NULL,
	[DELIVERY_TASK] [varchar](32) NULL,
	[DETAILED_DESCRIPTION] [varchar](4000) NULL,
	[DUE_DATE] [datetime] NULL,
	[ESCALATION] [varchar](50) NULL,
	[EXPECTED_START] [datetime] NULL,
	[FOLLOW_UP] [datetime] NULL,
	[GROUP_LIST] [varchar](4000) NULL,
	[IMPACT] [varchar](50) NULL,
	[KNOWLEDGE] [varchar](5) NULL,
	[LOCATION] [varchar](32) NULL,
	[MADE_SLA] [varchar](5) NULL,
	[NUMBER] [varchar](40) NOT NULL,
	[OPENED] [datetime] NULL,
	[OPENED_BY] [varchar](32) NULL,
	[ORDER] [int] NULL,
	[PARENT] [varchar](32) NULL,
	[PRIORITY] [varchar](50) NULL,
	[REASSIGNMENT_COUNT] [int] NULL,
	[REJECTION_GOTO] [varchar](32) NULL,
	[SERVICE_OFFERING] [varchar](32) NULL,
	[SHORT_DESCRIPTION] [varchar](80) NULL,
	[SKILLS] [varchar](4000) NULL,
	[SLA_DUE] [datetime] NULL,
	[STATE] [varchar](50) NULL,
	[TASK_TYPE] [varchar](80) NULL,
	[CREATED_BY] [varchar](40) NULL,
	[CREATED] [datetime] NULL,
	[DOMAIN] [varchar](32) NULL,
	[UPDATES] [int] NULL,
	[UPDATED_BY] [varchar](40) NULL,
	[UPDATED] [datetime] NULL,
	[TIME_WORKED] [int] NULL,
	[UPON_APPROVAL] [varchar](40) NULL,
	[UPON_REJECT] [varchar](40) NULL,
	[URGENCY] [varchar](50) NULL,
	[USER_INPUT] [varchar](4000) NULL,
	[BUSINESS_SERVICE] [varchar](32) NULL,
	[PROVIDER_SERVICE] [varchar](32) NULL,
	[KB_ARTICLE] [varchar](32) NULL,
	[COMPONENT_CATEGORY_L1] [varchar](40) NULL,
	[COMPONENT_CATEGORY_L2] [varchar](40) NULL,
	[COMPONENT_CATEGORY_L3] [varchar](40) NULL,
	[PROTOCOL_NOT_FOLLOWED] [varchar](5) NULL,
	[VARIABLES] [varchar](40) NULL,
	[WATCH_LIST] [varchar](4000) NULL,
	[WORKFLOW_ACTIVITY] [varchar](32) NULL,
	[ACTUAL_WORK_END] [varchar](40) NULL,
	[WORK_NOTES] [varchar](4000) NULL,
	[WORK_NOTES_LIST] [varchar](4000) NULL,
	[ACTUAL_WORK_START] [datetime] NULL,
	[ODS_CREATE_DATE] [datetime] NULL,
	[ODS_CREATED_BY] [varchar](50) NULL,
	[ODS_UPDATE_DATE] [datetime] NULL,
	[ODS_UPDATED_BY] [varchar](50) NULL,
 CONSTRAINT [PK_LAND_CHANGE_REQUEST] PRIMARY KEY CLUSTERED 
(
	[NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [sn].[LAND_CHANGE_REQUEST] ADD  DEFAULT (getutcdate()) FOR [ODS_CREATE_DATE]
GO

ALTER TABLE [sn].[LAND_CHANGE_REQUEST] ADD  DEFAULT (getutcdate()) FOR [ODS_UPDATE_DATE]
GO

CREATE INDEX idx01_LAND_CHANGE_REQUEST ON sn.LAND_CHANGE_REQUEST(ODS_UPDATE_DATE)
GO

PRINT 'Creating table LAND_CHANGE_REQUEST. Finished at: ' + CONVERT(VARCHAR(20), GETUTCDATE(), 120)
GO
