USE EDW2
GO

PRINT 'Updating Fact Chat Metric table for CA tails. Started at: ' + convert(varchar(50), getutcdate(), 120)

IF OBJECT_ID('tempdb..#FCM_TEMP') IS NOT NULL DROP TABLE #FCM_TEMP
SELECT	CUSTOMER_ID,Time_ID,DATE_ID,INCIDENT_ID , CHAT_DATE , 
CASE WHEN TAIL = 'C.GBIK' THEN 'C-GBIK'
	 WHEN TAIL = 'C.GBIA' THEN 'C-GBIA'
	 ELSE TAIL
END AS TAIL
INTO	#FCM_TEMP
FROM	dbo.FACT_CHAT_METRIC FCM
JOIN    dbo.DIM_AIRCRAFT DA on FCM.AIRCRAFT_ID=DA.AIRCRAFT_ID
WHERE	TAIL LIKE 'C%'
GO

ALTER TABLE #FCM_TEMP ADD IDC INT IDENTITY(1,1)
GO

CREATE INDEX IDX_TEMP_FCM ON #FCM_TEMP (IDC)
GO

DECLARE @IDC				INT
DECLARE @CNT				INT
DECLARE @EXIT_FLAG			INT

DECLARE @CUSTOMER_ID		NUMERIC(38,0)
DECLARE @Time_ID			NUMERIC(38,0)
DECLARE @DATE_ID			NUMERIC(38,0)
DECLARE @INCIDENT_ID		INT
DECLARE @CHAT_DATE			DATETIME
DECLARE @TAIL				VARCHAR(30)
DECLARE @AIRCRAFT_ID		NUMERIC(38,0)

SET @EXIT_FLAG = 0
SET @IDC = 1 

SELECT @CNT = COUNT(1) FROM #FCM_TEMP

WHILE @EXIT_FLAG = 0 
BEGIN
	
	SELECT	@CUSTOMER_ID =	CUSTOMER_ID, 
			@Time_ID	 =	Time_ID,
			@DATE_ID	 =	DATE_ID,
			@INCIDENT_ID =	INCIDENT_ID,
			@CHAT_DATE	 =	CHAT_DATE,	
			@TAIL		 =	TAIL
	FROM	#FCM_TEMP
	WHERE	IDC = @IDC

	SELECT	TOP 1 @AIRCRAFT_ID = AIRCRAFT_ID
	FROM	dbo.DIM_AIRCRAFT 
	WHERE	TAIL = @TAIL
	AND		AIRCRAFT_EFFECTIVE_DT < @CHAT_DATE
	ORDER	BY AIRCRAFT_EFFECTIVE_DT DESC

	UPDATE	dbo.FACT_CHAT_METRIC
	SET		AIRCRAFT_ID  = @AIRCRAFT_ID
	WHERE	CUSTOMER_ID	 = @CUSTOMER_ID 
	AND		Time_ID		 = @Time_ID
	AND		DATE_ID		 = @DATE_ID
	AND		INCIDENT_ID	 = @INCIDENT_ID

SET @IDC = @IDC + 1 
IF @IDC > @CNT SET @EXIT_FLAG = 1
END 

PRINT 'Finished at: ' + convert(varchar(50), getutcdate(), 120)
GO
