USE [ODS_LANDING]
GO

/****** Object:  Table [sn].[LAND_OUTAGE]    Script Date: 4/9/2014 7:37:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

PRINT 'Creating table LAND_OUTAGE. Started at: ' + CONVERT(VARCHAR(20), GETUTCDATE(), 120)
GO

IF EXISTS(SELECT 1 FROM sys.objects where name = 'LAND_OUTAGE') DROP TABLE [sn].[LAND_OUTAGE]

CREATE TABLE [sn].[LAND_OUTAGE](
	[OUTAGE_BEGIN] [datetime] NULL,
	[CONFIGURATION_ITEM] [varchar](32) NULL,
	[OUTAGE_DURATION] [int] NULL,
	[OUTAGE_END] [datetime] NULL,
	[MESSAGE] [varchar](32) NULL,
	[SHORT_DESCRIPTION] [varchar](100) NULL,
	[CREATED_BY] [varchar](40) NULL,
	[CREATED] [datetime] NULL,
	[SYS_ID] [varchar](32) NULL,
	[UPDATES] [int] NULL,
	[UPDATED_BY] [varchar](40) NULL,
	[UPDATED] [datetime] NULL,
	[TASK_NUMBER] [varchar](32) NULL,
	[TYPE] [varchar](40) NULL,
	[ALERT_24HR] [varchar](5) NULL,
	[ACTION] [varchar](4000) NULL,
	[ASSIGNED_TO] [varchar](32) NULL,
	[ASSIGNMENT_GROUP] [varchar](32) NULL,
	[BYPASS_DURATION] [int] NULL,
	[BUSINESS_AFFECTED] [varchar](40) NULL,
	[BYPASS_END] [datetime] NULL,
	[BYPASS_START] [datetime] NULL,
	[BYPASS_USER] [int] NULL,
	[CAUSED_BY_CHANGE] [varchar](32) NULL,
	[CONDITION] [varchar](40) NULL,
	[EVENT_DURATION] [int] NULL,
	[EVENT_START] [datetime] NULL,
	[EVENT_STOP] [datetime] NULL,
	[FLEETS_IMPACTED] [varchar](1024) NULL,
	[NUMBER_OF_CARE_CHATS] [int] NULL,
	[OUTAGE_CATEGORY_L1] [varchar](40) NULL,
	[OUTAGE_CATEGORY_L2] [varchar](40) NULL,
	[OUTAGE_CATEGORY_L3] [varchar](40) NULL,
	[REVENUE_IMPACT_DETAILED_DESC] [varchar](1000) NULL,
	[OUTAGE_NUMBER] [varchar](40) NOT NULL,
	[OUTAGE_STATE] [varchar](40) NULL,
	[PROCEDURAL] [varchar](4000) NULL,
	[REVENUE_IMPACT] [varchar](5) NULL,
	[ROOT_CAUSE_ANALYSIS] [varchar](4000) NULL,
	[SOLUTIONS] [varchar](4000) NULL,
	[TAILS_IN_FLIGHT] [int] NULL,
	[TS_CONDITION] [varchar](40) NULL,
	[USERS_ON_NETWORK] [int] NULL,
	[WATCH_LIST] [varchar](1024) NULL,
	[ODS_CREATE_DATE] [datetime] NULL,
	[ODS_CREATED_BY] [varchar](50) NULL,
	[ODS_UPDATE_DATE] [datetime] NULL,
	[ODS_UPDATED_BY] [varchar](50) NULL,
 CONSTRAINT [PK_LAND_OUTAGE] PRIMARY KEY CLUSTERED 
(
	[OUTAGE_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [sn].[LAND_OUTAGE] ADD  DEFAULT (getutcdate()) FOR [ODS_CREATE_DATE]
GO

ALTER TABLE [sn].[LAND_OUTAGE] ADD  DEFAULT (getutcdate()) FOR [ODS_UPDATE_DATE]
GO

CREATE INDEX idx01_LAND_OUTAGE ON sn.LAND_OUTAGE(ODS_UPDATE_DATE)
GO

PRINT 'Creating table LAND_OUTAGE. Finished at: ' + CONVERT(VARCHAR(20), GETUTCDATE(), 120)
GO
