USE EDW2
GO

PRINT 'Updating Fact Usage Metric table for CA tails. Started at: ' + convert(varchar(50), getutcdate(), 120)

IF OBJECT_ID('tempdb..#FUM_TEMP') IS NOT NULL DROP TABLE #FUM_TEMP
SELECT	ODS_USAGE_ID, USAGE_START_DATE, TAIL
INTO	#FUM_TEMP
FROM	dbo.FACT_USAGE_METRIC 
WHERE	TAIL LIKE 'C%'
GO

ALTER TABLE #FUM_TEMP ADD IDC INT IDENTITY(1,1)
GO

CREATE INDEX IDX_TEMP_FUM ON #FUM_TEMP (IDC)
GO

DECLARE @IDC				INT
DECLARE @CNT				INT
DECLARE @EXIT_FLAG			INT

DECLARE @ODS_USAGE_ID		NUMERIC(38,0)
DECLARE @USAGE_START_DATE	DATETIME
DECLARE @TAIL				VARCHAR(30)
DECLARE @AIRCRAFT_ID		NUMERIC(38,0)

SET @EXIT_FLAG = 0
SET @IDC = 1 

SELECT @CNT = COUNT(1) FROM #FUM_TEMP

WHILE @EXIT_FLAG = 0 
BEGIN
	SELECT	@ODS_USAGE_ID = ODS_USAGE_ID, 
			@USAGE_START_DATE = USAGE_START_DATE,
			@TAIL = TAIL
	FROM	#FUM_TEMP
	WHERE	IDC = @IDC

	SELECT	TOP 1 @AIRCRAFT_ID = AIRCRAFT_ID
	FROM	dbo.DIM_AIRCRAFT 
	WHERE	TAIL = @TAIL
	AND		AIRCRAFT_EFFECTIVE_DT < @USAGE_START_DATE
	ORDER	BY AIRCRAFT_EFFECTIVE_DT DESC

	UPDATE	dbo.FACT_USAGE_METRIC
	SET		AIRCRAFT_ID = @AIRCRAFT_ID
	WHERE	ODS_USAGE_ID = @ODS_USAGE_ID 

SET @IDC = @IDC + 1 
IF @IDC > @CNT SET @EXIT_FLAG = 1
END 

PRINT 'Finished at: ' + convert(varchar(50), getutcdate(), 120)
GO
