USE [ODS_STAGING]
GO

/****** Object:  Table [finance].[STAGE_SCOOT]    Script Date: 11/19/2013 12:05:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [finance].[STAGE_SCOOT](
	[ODS_SCOOT_ID] [numeric](38, 0) IDENTITY(1,1) NOT NULL,
	[DATE_ID] [numeric](38, 0) NULL,
	[DATE] [datetime] NULL,
	[MONTHLY_SERVICE_FEE] [numeric](16, 2) NULL,
	[CONNECTIVITY_FEE] [numeric](16, 2) NULL,
	[CONTECT_DELIVERY_FEE] [numeric](16, 2) NULL,
	[ODS_CREATE_DATE] [datetime] NOT NULL,
	[ODS_CREATED_BY] [nvarchar](50) NOT NULL,
	[ODS_UPDATE_DATE] [datetime] NOT NULL,
	[ODS_UPDATED_BY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_STAGE_SCOOT] PRIMARY KEY CLUSTERED 
(
	[ODS_SCOOT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [finance].[STAGE_SCOOT] ADD  DEFAULT (getutcdate()) FOR [ODS_CREATE_DATE]
GO

ALTER TABLE [finance].[STAGE_SCOOT] ADD  DEFAULT (getutcdate()) FOR [ODS_UPDATE_DATE]
GO


